version: 2

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^!\approve'
  reset_on_push:
    enabled: true

groups:
  code-admins:
    required: 2
    users:
      - thetrentus
      - thetrentus-review
